"""Repository ports (interfaces).

Defined in the domain layer, implemented in infrastructure/persistence.
This is the mechanism that keeps the domain ignorant of SQLAlchemy /
PostgreSQL: application services depend on these Protocols, never on
concrete repositories.
"""
from __future__ import annotations

import uuid
from typing import Protocol

from app.domain.audit.entities import AuditEvent
from app.domain.competitions.entities import Competition, Season
from app.domain.matches.entities import Match, MatchResult
from app.domain.phases.entities import Phase, Pool
from app.domain.teams.entities import Team
from app.domain.users.entities import User


class SeasonRepository(Protocol):
    def add(self, season: Season) -> Season: ...
    def get(self, season_id: uuid.UUID) -> Season | None: ...
    def list(self) -> list[Season]: ...


class CompetitionRepository(Protocol):
    def add(self, competition: Competition) -> Competition: ...
    def get(self, competition_id: uuid.UUID) -> Competition | None: ...
    def list(self, limit: int = 50, offset: int = 0) -> tuple[list[Competition], int]: ...
    def list_published(self, limit: int = 50, offset: int = 0) -> tuple[list[Competition], int]: ...
    def update(self, competition: Competition) -> Competition: ...


class TeamRepository(Protocol):
    def add(self, team: Team) -> Team: ...
    def get(self, team_id: uuid.UUID) -> Team | None: ...
    def list_by_competition(self, competition_id: uuid.UUID) -> list[Team]: ...
    def update(self, team: Team) -> Team: ...


class PhaseRepository(Protocol):
    def add(self, phase: Phase) -> Phase: ...
    def get(self, phase_id: uuid.UUID) -> Phase | None: ...
    def list_by_competition(self, competition_id: uuid.UUID) -> list[Phase]: ...


class PoolRepository(Protocol):
    def add(self, pool: Pool) -> Pool: ...
    def get(self, pool_id: uuid.UUID) -> Pool | None: ...
    def list_by_phase(self, phase_id: uuid.UUID) -> list[Pool]: ...
    def update(self, pool: Pool) -> Pool: ...


class MatchRepository(Protocol):
    def add(self, match: Match) -> Match: ...
    def add_many(self, matches: list[Match]) -> list[Match]: ...
    def get(self, match_id: uuid.UUID) -> Match | None: ...
    def list_by_competition(self, competition_id: uuid.UUID) -> list[Match]: ...
    def list_by_pool(self, pool_id: uuid.UUID) -> list[Match]: ...
    def update(self, match: Match) -> Match: ...
    def delete_unplayed_by_pool(self, pool_id: uuid.UUID) -> None: ...
    def has_played_matches(self, pool_id: uuid.UUID) -> bool: ...


class MatchResultRepository(Protocol):
    def add(self, result: MatchResult) -> MatchResult: ...
    def get_by_match(self, match_id: uuid.UUID) -> MatchResult | None: ...
    def update(self, result: MatchResult) -> MatchResult: ...
    def list_by_pool(self, pool_id: uuid.UUID) -> list[MatchResult]: ...


class UserRepository(Protocol):
    def get(self, user_id: uuid.UUID) -> User | None: ...
    def get_by_email(self, email: str) -> User | None: ...
    def add(self, user: User) -> User: ...


class AuditRepository(Protocol):
    def add(self, event: AuditEvent) -> AuditEvent: ...
    def list_by_entity(self, entity_type: str, entity_id: uuid.UUID) -> list[AuditEvent]: ...
    def list_all(self, limit: int = 50, offset: int = 0) -> tuple[list[AuditEvent], int]: ...
